'use strict';
// Tutti i laboratori usano soltanto SVG e JavaScript del browser.
const B='#276aa0', O='#b75a31', G='#236454', TAU=2*Math.PI;
const fmt=(x,n=4)=>Math.abs(x)<1e-12?'0':Number(x.toPrecision(n)).toLocaleString('it-IT',{maximumFractionDigits:10});
const seq=(a,b,n=240)=>Array.from({length:n},(_,i)=>a+(b-a)*i/(n-1));
const gcd=(a,b)=>b?gcd(b,a%b):a;
function isqrt(n){if(n<2n)return n;let x=n,y=(x+1n)/2n;while(y<x){x=y;y=(x+n/x)/2n;}return x;}
function rootInterval(d){const s=10n**BigInt(d),p=isqrt(2n*s*s);return {s,p,lower:Number(p)/Number(s),upper:Number(p+1n)/Number(s)};}
function roots(n,r,phi){const R=r**(1/n);return Array.from({length:n},(_,k)=>{const a=(phi+TAU*k)/n;return [R*Math.cos(a),R*Math.sin(a)];});}
function multiply(rho,theta){return [rho*(Math.cos(theta)-.5*Math.sin(theta)),rho*(Math.sin(theta)+.5*Math.cos(theta))];}
function pascal(n){let row=[1];for(let j=1;j<=n;j++)row.push(row[j-1]*(n-j+1)/j);return row;}
function escapeText(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function plot(title,xmin,xmax,ymin,ymax,{equal=false,xlabel='x',ylabel='y'}={}){
  const W=700,H=390,L=58,T=32,R=22,D=52;
  let w=W-L-R,h=H-T-D,ox=L,oy=T;
  if(equal){const scale=Math.min(w/(xmax-xmin),h/(ymax-ymin));const nw=(xmax-xmin)*scale,nh=(ymax-ymin)*scale;ox+=(w-nw)/2;oy+=(h-nh)/2;w=nw;h=nh;}
  const X=x=>ox+(x-xmin)*w/(xmax-xmin),Y=y=>oy+h-(y-ymin)*h/(ymax-ymin);
  let elements=[];
  const line=(x1,y1,x2,y2,color='#cdd8d1',dash='')=>elements.push(`<line x1="${X(x1)}" y1="${Y(y1)}" x2="${X(x2)}" y2="${Y(y2)}" stroke="${color}" stroke-width="1.6" ${dash?'stroke-dasharray="'+dash+'"':''}/>`);
  const label=(x,y,t,c='#60706a',dx=0,dy=0)=>elements.push(`<text x="${X(x)+dx}" y="${Y(y)+dy}" fill="${c}" text-anchor="middle">${escapeText(t)}</text>`);
  for(let j=0;j<=4;j++){const x=xmin+(xmax-xmin)*j/4,y=ymin+(ymax-ymin)*j/4;line(x,ymin,x,ymax,'#edf0eb');line(xmin,y,xmax,y,'#edf0eb');label(x,ymin,fmt(x,3),'#60706a',0,22);label(xmin,y,fmt(y,3),'#60706a',-30,4);}
  if(ymin<=0&&ymax>=0)line(xmin,0,xmax,0,'#94a79b');
  if(xmin<=0&&xmax>=0)line(0,ymin,0,ymax,'#94a79b');
  const path=(points,color=B,fill='none',dash='',width=2)=>{if(!points.length)return;elements.push(`<path d="${points.map(([x,y],i)=>(i?'L':'M')+X(x).toFixed(3)+','+Y(y).toFixed(3)).join(' ')}" stroke="${color}" fill="${fill}" stroke-width="${width}" ${dash?'stroke-dasharray="'+dash+'"':''}/>`);};
  const circle=(x,y,r,color=B,fill='none',dash='')=>elements.push(`<ellipse cx="${X(x)}" cy="${Y(y)}" rx="${r*w/(xmax-xmin)}" ry="${r*h/(ymax-ymin)}" stroke="${color}" fill="${fill}" stroke-width="2" ${dash?'stroke-dasharray="'+dash+'"':''}/>`);
  const point=(x,y,color=B,open=false)=>elements.push(`<circle cx="${X(x)}" cy="${Y(y)}" r="4.5" fill="${open?'white':color}" stroke="${color}" stroke-width="2"/>`);
  const rect=(x1,y1,x2,y2,fill)=>elements.push(`<rect x="${Math.min(X(x1),X(x2))}" y="${Math.min(Y(y1),Y(y2))}" width="${Math.abs(X(x2)-X(x1))}" height="${Math.abs(Y(y2)-Y(y1))}" fill="${fill}"/>`);
  const svg=()=>`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${escapeText(title)}"><title>${escapeText(title)}</title><text x="350" y="18" text-anchor="middle" fill="${G}">${escapeText(title)}</text>${elements.join('')}<text x="350" y="383" text-anchor="middle" fill="#60706a">${escapeText(xlabel)}</text><text x="12" y="26" fill="#60706a">${escapeText(ylabel)}</text></svg>`;
  return {line,label,path,circle,point,rect,svg};
}
const powerChoices={'−2/7':[-2,7],'4/5':[4,5],'6/5':[6,5],'π':[Math.PI,0],'1/√2':[1/Math.SQRT2,0],'−1/5':[-1,5],'2':[2,1],'3':[3,1],'1/2':[1,2]};
function realPower(x,key){const [m,n]=powerChoices[key],a=n?m/n:m;if(x===0)return a>0?0:NaN;if(x<0){if(!n||n%2===0)return NaN;return (Math.abs(m)%2===0?1:-1)*Math.abs(x)**a;}return x**a;}
function curve(p,f,a,b,lo,hi,color=B,n=800){let part=[];const flush=()=>{if(part.length>1)p.path(part,color);part=[];};for(const x of seq(a,b,n)){const y=f(x);if(!Number.isFinite(y)||y<lo||y>hi){flush();continue;}if(part.length&&Math.abs(y-part.at(-1)[1])>(hi-lo)*.2)flush();part.push([x,y]);}flush();}
function bisect(steps){let a=-.8,b=-.7;const f=x=>Math.exp(x)+x*x-1;for(let i=0;i<steps;i++){const m=(a+b)/2;if(f(m)>0)a=m;else b=m;}return {a,b};}
// Valutazioni numeriche per l'esplorazione; le garanzie sono spiegate nella teoria.
function sequenceN(kind,eps){return kind==='1/n'?Math.floor(1/eps)+1:kind==='(n+1)/(n−1)'?Math.floor(1+2/eps)+1:Math.floor(1/eps)+1;}
function deltaCondition(eps,delta){return delta*(2+delta)<=eps;}
function bisection(steps){let a=0,b=1;const f=x=>x*x*x+x-1;for(let j=0;j<steps;j++){const m=(a+b)/2;if(f(m)===0){a=b=m;break;}if(f(a)*f(m)<0)b=m;else a=m;}return {a,b,mid:(a+b)/2,error:(b-a)/2};}
const labs={
1:{controls:[['tipo','Successione',['1/n','(n+1)/(n−1)','(−1)ⁿ/n'],'1/n'],['eps','Precisione ε',.01,1,.01,.2],['count','Punti visibili',10,150,1,40]],render(v){const L=v.tipo==='(n+1)/(n−1)'?1:0,f=n=>v.tipo==='1/n'?1/n:v.tipo==='(n+1)/(n−1)'?(n+1)/(n-1):(-1)**n/n,start=v.tipo==='(n+1)/(n−1)'?2:1,N=sequenceN(v.tipo,v.eps),p=plot('Una fascia, poi tutta la coda',0,v.count+1,L-1.2,L+2.2,{xlabel:'indice n',ylabel:'aₙ'});p.rect(0,L-v.eps,v.count+1,L+v.eps,'#e3eee5');p.line(0,L,v.count+1,L,G,'4 4');for(let n=start;n<=v.count;n++)p.point(n,f(n),Math.abs(f(n)-L)<v.eps?B:O);if(N<=v.count)p.line(N,L-1.2,N,L+2.2,G,'4 4');return[p.svg(),`Limite ${L}. Un indice sufficiente è <strong>N = ${N}</strong>: tutti i termini con n ≥ N sono nella fascia aperta. ${N>v.count?'N è oltre la finestra: aumenta i punti visibili.':''} La fascia colorata indica le quote L ± ε; i bordi non sono ammessi nella disuguaglianza stretta.`];}},
2:{controls:[['q','Ragione q',-1.5,1.5,.05,.8],['count','Punti visibili',5,40,1,20]],render(v){const ymax=Math.max(1.3,Math.min(30,Math.abs(v.q)**v.count*1.1)),p=plot('Successione geometrica qⁿ',0,v.count+1,-ymax,ymax,{xlabel:'indice n',ylabel:'qⁿ'});for(let n=1;n<=v.count;n++){const y=v.q**n;if(Math.abs(y)<=ymax)p.point(n,y,n%2?O:B);}const message=v.q>1?'Diverge a +∞.':Math.abs(v.q-1)<1e-10?'È costante: limite 1.':Math.abs(v.q)<1?'Converge a zero.':v.q<=-1?'Non ha limite: le code pari e dispari sono incompatibili.':'Converge a zero.';return[p.svg(),`q = ${fmt(v.q)}. ${message} I punti fuori scala non sono disegnati; una finestra troncata non è un limite finito.`];}},
3:{controls:[['n','Indice n',1,200,1,20]],render(v){const u=n=>Math.exp(n*Math.log1p(1/n)),w=n=>Math.exp((n+1)*Math.log1p(1/n)),p=plot('uₙ cresce, vₙ decresce',1,Math.max(v.n,10),1.9,4.1,{xlabel:'indice n',ylabel:'valore'});p.path(seq(1,Math.max(v.n,10),180).map(n=>[n,u(n)]),B);p.path(seq(1,Math.max(v.n,10),180).map(n=>[n,w(n)]),O);p.line(1,Math.E,Math.max(v.n,10),Math.E,G,'4 4');p.point(v.n,u(v.n),B);p.point(v.n,w(v.n),O);return[p.svg(),`uₙ = ${fmt(u(v.n),10)} ≤ e ≤ vₙ = ${fmt(w(v.n),10)}. Ampiezza dell’intervallo: ${fmt(w(v.n)-u(v.n),8)}. Blu: (1 + 1/n)ⁿ; arancio: (1 + 1/n)ⁿ⁺¹. Le curve collegano i valori per leggibilità; le successioni si valutano agli indici interi.`];}},
4:{controls:[['ratio','Rapporto',['log n / nᵅ','nᵅ / aⁿ'],'log n / nᵅ'],['alpha','Esponente α',.1,5,.1,1],['a','Base a',1.1,3,.1,2],['max','Indice finale',20,300,1,60]],render(v){const f=n=>v.ratio==='log n / nᵅ'?Math.log(n)/n**v.alpha:Math.exp(v.alpha*Math.log(n)-n*Math.log(v.a)),points=seq(1,v.max).map(n=>[n,f(n)]),peak=Math.max(...points.map(x=>x[1])),p=plot('Rapporto tra due crescite',1,v.max,0,Math.max(.01,peak*1.1),{xlabel:'indice n',ylabel:'rapporto'});p.path(points,B);p.point(v.max,f(v.max),O);return[p.svg(),`Rapporto al bordo: ${fmt(f(v.max),7)}. Per α > 0 e a > 1 il limite è zero. Un eventuale aumento iniziale è compatibile con il limite: la gerarchia riguarda la coda.`];}},
5:{controls:[['p','n = 10ᵖ',1,16,1,7]],render(v){const n=10**v.p,raw=n*(Math.sqrt(n*n+1)-n),stable=1/(Math.sqrt(1+1/(n*n))+1),direct=(1+1/n)**n,good=Math.exp(n*Math.log1p(1/n)),p=plot('Sottrazione diretta e formula razionalizzata',1,16,-.1,1.1,{xlabel:'esponente p in n = 10ᵖ',ylabel:'risultato'});for(let j=1;j<=16;j++){const t=10**j;p.point(j,t*(Math.sqrt(t*t+1)-t),O);p.point(j,1/(Math.sqrt(1+1/(t*t))+1),B);}p.line(1,.5,16,.5,G,'4 4');return[p.svg(),`n = 10<sup>${v.p}</sup>. Calcolo diretto (arancio): ${fmt(raw,12)}; razionalizzato (blu): ${fmt(stable,12)}; limite matematico 1/2. Per (1 + 1/n)ⁿ: diretto ${fmt(direct,12)}, forma stabile ${fmt(good,12)}. Le differenze dipendono dalla precisione numerica del browser.`];}},
6:{controls:[['f','Funzione',['1/x','(x²+3x−1)/(x+2)','3x+√x'],'(x²+3x−1)/(x+2)'],['x','Ingresso x',-8,8,.1,4]],render(v){const rational=v.f==='(x²+3x−1)/(x+2)',root=v.f==='3x+√x',f=x=>rational?x+1-3/(x+2):root?3*x+Math.sqrt(x):1/x,p=plot('Curva e retta di confronto',-8,8,-12,18);curve(p,f,-8,rational?-2.001:root?-.001:-.001,-12,18,B);curve(p,f,rational?-1.999:root?0:.001,8,-12,18,B);if(rational){p.line(-8,-7,8,9,O,'4 4');p.line(-2,-12,-2,18,G,'4 4');}else if(!root){p.line(-8,0,8,0,O,'4 4');p.line(0,-12,0,18,G,'4 4');}else curve(p,x=>3*x,0,6,-12,18,O);const y=f(v.x),ok=Number.isFinite(y);if(ok&&y>=-12&&y<=18)p.point(v.x,y,G);return[p.svg(),root?`3x + √x ha rapporto con x tendente a 3, ma la differenza con 3x è √x e diverge. ${v.x<0?'Il punto scelto non è nel dominio.':`Differenza al punto: ${fmt(Math.sqrt(v.x))}.`} Nessun asintoto obliquo.`:rational?`Asintoti: x = −2 e y = x + 1. ${ok?`Differenza f(x) − (x+1) = ${fmt(y-v.x-1)}.`:'x = −2 non appartiene al dominio.'}`:`Asintoti: x = 0 e y = 0. ${ok?`f(${fmt(v.x)}) = ${fmt(y)}.`:'x = 0 non appartiene al dominio.'}`];}},
7:{controls:[['tipo','Intorno di zero',['x + 1','Salto','Oscillazione'],'x + 1'],['c','Valore f(0)',-2,3,.1,0]],render(v){const p=plot('Il limite ignora il valore nel punto',-2,2,-2.5,3.5),f=x=>v.tipo==='x + 1'?x+1:v.tipo==='Salto'?(x<0?-1:1):Math.sin(1/x);curve(p,f,-2,-.015,-2.5,3.5,B,1300);curve(p,f,.015,2,-2.5,3.5,B,1300);if(v.tipo==='x + 1')p.point(0,1,B,true);if(v.tipo==='Salto'){p.point(0,-1,B,true);p.point(0,1,B,true);}p.point(0,v.c,O);return[p.svg(),v.tipo==='x + 1'?`Limite 1; f(0) = ${fmt(v.c)}. ${Math.abs(v.c-1)<1e-9?'La funzione è continua in zero.':'Il difetto si elimina solo assegnando f(0) = 1.'}`:v.tipo==='Salto'?'Limiti laterali −1 e 1: nessun valore assegnato in zero elimina il salto.':'Il limite non esiste: nessun valore in zero elimina le oscillazioni. Una piccola zona centrale è omessa perché non si possono disegnare infinite oscillazioni.'];}},
8:{controls:[['eps','Precisione ε',.05,2,.05,.5],['delta','Raggio δ',.01,1.5,.01,.1]],render(v){const p=plot('Fascia ε e intervallo δ per x² in 1',-.6,2.6,-.4,7);p.rect(-.6,1-v.eps,2.6,1+v.eps,'#e3eee5');p.rect(1-v.delta,-.4,1+v.delta,7,'#276aa018');curve(p,x=>x*x,-.6,2.6,-.4,7,B);p.point(1,1,G);p.line(1-v.delta,-.4,1-v.delta,7,O,'4 4');p.line(1+v.delta,-.4,1+v.delta,7,O,'4 4');const bound=v.delta*(2+v.delta),safe=Math.min(1,v.eps/3);return[p.svg(),`Per 0 < |x−1| < δ, l’errore è strettamente minore di δ(2+δ) = ${fmt(bound)}. ${deltaCondition(v.eps,v.delta)?'<strong>La tua δ garantisce la fascia per tutti gli ingressi ammessi.</strong>':'La tua δ è troppo grande: esistono ingressi a destra con errore ≥ ε.'} Una scelta sempre valida: δ = min(1, ε/3) = ${fmt(safe)}. Il risultato deriva da una stima, non dai punti campionati.`];}},
9:{controls:[['f','Rapporto',['sin t / t','(1−cos t)/t²','log(1+t)/t','(eᵗ−1)/t'],'sin t / t'],['zoom','Raggio della finestra',.02,1,.02,.5]],render(v){const f=t=>v.f==='sin t / t'?Math.sin(t)/t:v.f==='(1−cos t)/t²'?2*(Math.sin(t/2)/t)**2:v.f==='log(1+t)/t'?Math.log1p(t)/t:Math.expm1(t)/t,L=v.f==='(1−cos t)/t²'?.5:1,p=plot('Il limite del rapporto vicino a zero',-v.zoom,v.zoom,0,2.5);curve(p,f,-v.zoom,-v.zoom/1000,0,2.5,B);curve(p,f,v.zoom/1000,v.zoom,0,2.5,B);p.line(-v.zoom,L,v.zoom,L,O,'4 4');p.point(0,L,B,true);return[p.svg(),`Limite ${L}. In zero il rapporto originale è escluso; il cerchio vuoto indica il valore del prolungamento continuo. log(1+t) richiede t > −1. Forme stabili sono usate per ridurre la cancellazione numerica.`];}},
10:{controls:[['max','Estremo della finestra',5,100,1,20],['x','Punto di confronto',1,50,1,10]],render(v){const p=plot('3x + √x (blu) e 3x (arancio)',0,v.max,0,3*v.max+Math.sqrt(v.max));curve(p,x=>3*x+Math.sqrt(x),0,v.max,0,3*v.max+Math.sqrt(v.max),B);curve(p,x=>3*x,0,v.max,0,3*v.max+Math.sqrt(v.max),O);const q=plot('Differenza √x che non tende a zero',0,v.max,0,Math.sqrt(v.max)*1.1);curve(q,Math.sqrt,0,v.max,0,Math.sqrt(v.max)*1.1,B);return[p.svg()+q.svg(),`Al punto x = ${v.x}, f(x)/(3x) = ${fmt(1+1/(3*Math.sqrt(v.x)))} si avvicina a 1; f(x) − 3x = ${fmt(Math.sqrt(v.x))} cresce. Un piccolo errore relativo può convivere con un errore assoluto illimitato.`];}},
11:{controls:[['T','Temperatura normalizzata T',.5,2,.1,1]],render(v){const planck=l=>l<=0?0:l**-5/Math.expm1(1/(l*v.T)),classic=l=>v.T*l**-4,max=Math.max(...seq(.02,2,400).map(planck))*1.2,p=plot('Planck (blu) e Rayleigh–Jeans (arancio)',0,2,0,max,{xlabel:'lunghezza d’onda normalizzata',ylabel:'densità normalizzata'});curve(p,planck,.01,2,0,max,B,1600);curve(p,classic,.01,2,0,max,O,1600);return[p.svg(),`Unità adimensionali: j(λ)=λ⁻⁵/(exp(1/(λT))−1). Il modello classico Tλ⁻⁴ coincide asintoticamente a grandi λ; a λ→0 diverge mentre Planck tende a zero. T = ${fmt(v.T)}. Il tratto classico fuori scala è omesso.`];}},
12:{controls:[['R','Resistenza R',0,3,.1,1],['L','Induttanza L',.2,3,.1,1],['C','Capacità C',.2,3,.1,1]],render(v){const f=w=>Math.hypot(v.R,v.L*w-1/(v.C*w)),w0=1/Math.sqrt(v.L*v.C),xmax=Math.max(5,w0*1.7),ymax=Math.max(8,v.L*xmax*1.2,v.R+1),p=plot('Impedenza RLC in unità normalizzate',0,xmax,0,ymax,{xlabel:'pulsazione ω',ylabel:'Z(ω)'});curve(p,f,.015,xmax,0,ymax,B,1200);curve(p,w=>v.L*w,.015,xmax,0,ymax,O);p.point(w0,v.R,G);p.line(w0,0,w0,v.R,G,'4 4');return[p.svg(),`Minimo Z = R = ${fmt(v.R)} alla pulsazione ω₀ = 1/√(LC) = ${fmt(w0)}. Per ω→0⁺, Z→+∞; per ω→∞, l’asintoto è Z=Lω (arancio). R, L e C sono normalizzati.`];}},
13:{controls:[['steps','Suddivisioni',0,25,1,5]],render(v){const r=bisection(v.steps),p=plot('f(x)=x³+x−1 e intervallo che contiene lo zero',0,1,-1.1,1.1);p.rect(r.a,-1.1,r.b,1.1,'#e3eee5');curve(p,x=>x*x*x+x-1,0,1,-1.1,1.1,B);p.point(r.a,r.a**3+r.a-1,O);p.point(r.b,r.b**3+r.b-1,O);p.line(r.mid,-1.1,r.mid,1.1,G,'4 4');return[p.svg(),`Dopo ${v.steps} suddivisioni: c ∈ [${r.a.toPrecision(12)}, ${r.b.toPrecision(12)}]. Punto medio ${r.mid.toPrecision(12)}; errore assoluto ≤ <strong>${r.error.toExponential(4)}</strong>. Continuità, segni opposti e intervalli annidati danno la garanzia. A tanti passi la fascia diventa più sottile di un pixel.`];}},
14:{controls:[['f','Funzione',['Continua: x³−x','Discontinua: gradino'],'Continua: x³−x'],['lambda','Quota λ',-.3,.3,.01,.1]],render(v){const continuous=v.f==='Continua: x³−x',f=x=>continuous?x**3-x:(x<0?-1:1),p=plot('Il valore intermedio è assunto?',-1.5,1.5,-2,2);curve(p,f,-1.5,-.001,-2,2,B);curve(p,f,.001,1.5,-2,2,B);if(continuous)p.point(0,0,B);else{p.point(0,-1,B,true);p.point(0,1,B);}p.line(-1.5,v.lambda,1.5,v.lambda,O,'4 4');return[p.svg(),continuous?`La funzione continua su [−1.5,1.5] passa da −1.875 a 1.875: ogni λ selezionata è assunta almeno una volta. Il teorema non garantisce unicità.`:`Il gradino ha solo uscite −1 e 1: λ=${fmt(v.lambda)} non è assunta. Manca la continuità, quindi il teorema dei valori intermedi non si applica.`];}},
15:{controls:[['y','Ingresso dell’inversa y',-6,6,.1,2]],render(v){const p=plot('x³ (blu), radice cubica (arancio), y=x',-3,3,-3,3,{equal:true});curve(p,x=>x**3,-3,3,-3,3,B);curve(p,Math.cbrt,-3,3,-3,3,O);p.line(-3,-3,3,3,'#94a79b','4 4');const x=Math.cbrt(v.y);if(Math.abs(v.y)<=3){p.point(x,v.y,B);p.point(v.y,x,O);}return[p.svg(),`f(x)=x³ è continua e strettamente crescente su ℝ. L’inversa continua è g(y)=∛y: g(${fmt(v.y)})=${fmt(x)}. I punti (g(y),y) e (y,g(y)) sono simmetrici rispetto a y=x; se escono dalla finestra restano definiti.`];}}
};
function mount(el){const id=Number(el.dataset.lab),lab=labs[id],values={},defaults={};
  el.innerHTML=`<div class="lab-top"><strong>ESPLORA · LABORATORIO ${id.toString().padStart(2,'0')}</strong><button type="button">Ripristina</button></div><div class="controls"></div><div class="graph"></div><div class="result" aria-live="polite" aria-atomic="true"></div>`;
  const controls=el.querySelector('.controls');
  lab.controls.forEach(c=>{const [key,title,a,b,step,initial]=c,select=Array.isArray(a),value=select?b:initial;values[key]=defaults[key]=value;const label=document.createElement('label');label.className='control';label.innerHTML=`<span>${title}<output id="val-${id}-${key}"></output></span>`;const input=document.createElement(select?'select':'input');input.id=`control-${id}-${key}`;input.setAttribute('aria-label',`Laboratorio ${id}: ${title}`);
    if(select)a.forEach(text=>{const op=document.createElement('option');op.textContent=text;op.value=text;input.append(op);});else{input.type='range';input.min=a;input.max=b;input.step=step;}input.value=value;input.dataset.key=key;label.append(input);controls.append(label);input.addEventListener('input',()=>{values[key]=select?input.value:Number(input.value);render();});
  });
  function render(){const [svg,text]=lab.render(values);el.querySelector('.graph').innerHTML=svg;el.querySelector('.result').innerHTML=text;lab.controls.forEach(c=>{el.querySelector(`#val-${id}-${c[0]}`).textContent=Array.isArray(c[2])?'':fmt(values[c[0]],5);});}
  el.querySelector('button').addEventListener('click',()=>{Object.assign(values,defaults);controls.querySelectorAll('input,select').forEach(x=>x.value=values[x.dataset.key]);render();});render();
}
if(typeof document!=='undefined'){
  document.querySelectorAll('[data-lab]').forEach(el=>{try{mount(el);}catch(e){el.innerHTML='<p class="avviso">Questo laboratorio non è disponibile nel browser in uso. Prova una versione aggiornata di Edge, Firefox, Chrome o Safari.</p>';console.error(e);}});
  const exerciseDetails=[...document.querySelectorAll('details.esercizio')];let printState=[];
  window.addEventListener('beforeprint',()=>{printState=exerciseDetails.map(d=>d.open);exerciseDetails.forEach(d=>d.open=true);});
  window.addEventListener('afterprint',()=>exerciseDetails.forEach((d,i)=>d.open=printState[i]));
  document.querySelector('#stampa').addEventListener('click',()=>window.print());
  if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));}}),{rootMargin:'-10% 0px -70% 0px'});document.querySelectorAll('h2[id]').forEach(h=>observer.observe(h));}
}
if(typeof module!=='undefined')module.exports={labs,bisection,sequenceN,deltaCondition};
